server.port=80
server.address=0.0.0.0

# TẮT HOÀN TOÀN DB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# tránh lỗi bean
spring.main.allow-bean-definition-overriding=true